name: 'Unity Game Hosting'
inputs:
  BuildName:
    required: true
    type: string
    description: "Name of the new build. Input will be sanitised"
  BuildFilesDirectory:
    required: true
    type: string
  BuildOsFamily:
    required: true
    type: choice
    options:
     - "LINUX"
     - "WINDOWS"
  Project:
    required: true
    type: string
    description: "Unity Game Services Project-id, eg XXXX-XXXX-XXX-XXX"
  Environment:
    required: true
    type: string
    description: "Ugs Environment name that the build will reside in"
  #secrets: # gr: these should be secrets, but... can I use them here?? they get passed in via with: still...
  Key:
    required: true
    type: string
    description: "Service account Key-id"
  Secret:
    required: true
    type: string
    description: "Service account Key's secret"


runs:
  using: 'node16'
  main: 'UnityGameHostingBuildUpload.js'
